"""Generate the 800 px responsive variants and js/media.js (intrinsic sizes, so every
<img> gets width/height and never shifts the layout while loading).
Run after adding or replacing images:  python3 tools/build_images.py
Requires Pillow (pip install pillow)."""
import json, os
from PIL import Image

ROOT = os.path.join(os.path.dirname(__file__), '..')
IMG = os.path.join(ROOT, 'img')
SMALL_W = 800

meta = {}
for dirpath, dirs, files in os.walk(IMG):
    dirs[:] = [d for d in dirs if d != 'sm']
    for f in sorted(files):
        if not f.endswith('.webp'):
            continue
        src = os.path.join(dirpath, f)
        rel = os.path.relpath(src, IMG).replace(os.sep, '/')
        im = Image.open(src)
        w, h = im.size
        entry = [w, h]
        if w > SMALL_W * 1.15:
            out = os.path.join(dirpath, 'sm', f)
            if not os.path.exists(out) or os.path.getmtime(out) < os.path.getmtime(src):
                os.makedirs(os.path.dirname(out), exist_ok=True)
                im.resize((SMALL_W, round(h * SMALL_W / w)), Image.LANCZOS).save(out, 'WEBP', quality=80, method=6)
            entry.append(1)  # has an 800w variant
        meta[rel] = entry

with open(os.path.join(ROOT, 'js', 'media.js'), 'w') as fh:
    fh.write('/* Generated by tools/build_images.py — [width, height, has800wVariant] per image. */\n')
    fh.write('window.MEDIA=' + json.dumps(meta, separators=(',', ':')) + ';\n')
print(len(meta), 'images')
